name: Rust Build

on:
  workflow_dispatch:

  push:

jobs:
  build:
    runs-on:
      - self-hosted
      - arm64
      - rust

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust

      - uses: ./.github/actions/cargo-cache

      - uses: ./.github/actions/cargo-fmt

      - uses: ./.github/actions/cargo-clippy

      - uses: ./.github/actions/cargo-test

      - uses: ./.github/actions/cargo-build
